// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbydiennwirsoccbngvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZieWRpZW5ud2lyc29jY2JuZ3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTI0MTQsImV4cCI6MjA3MTA4ODQxNH0.d3WJbHq0IpTUDmtxqCvPiIctD8MVKzDSHvWTX2KwY7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});